<a href="https://colab.research.google.com/github/8AquA8/2024-SRC-Summer-Program/blob/main/SRC_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **The Ising Model of a Ferromagnet**

In an **ideal paramagnet**, each microscopic magnetic dipole responds only to the external magnetic field (if any); the dipoles have no inherent tendency to point parallel (or antiparallel) to their immediate neighbors. In the real world, however, atomic dipoles are influenced by their neighbors: **There is always some preference for neighboring dipoles to align either parallel or antiparallel.** In some materials, this preference is due to ordinary magnetic forces between the dipoles. In more dramatic examples (such as iron), however, the alignment of neighboring dipoles is due to complicated quantum-mechanical effects involving the Pauli exclusion principle. Either way, there is a contribution to the energy that is greater or less, depending on the relative alignment of neighboring dipoles.

**When neighboring dipoles align parallel to each other, even in the absence of an external field, we call the material a ferromagnet** (in honor of iron, the most familiar example). When neighboring dipoles align antiparallel, we call the material an antiferromagnet (examples include Cr, NiO, and FeO). In this section, I’ll discuss ferromagnets, although most of the same ideas can also be applied to antiferromagnets.

The long-range order of a ferromagnet manifests itself as a net nonzero magnetization. **Raising the temperature, however, causes random fluctuations that decrease the overall magnetization.** For every ferromagnet, there is a certain critical temperature, called the **Curie temperature**, at which the net magnetization becomes zero (when there is no external field). **Above the Curie temperature a ferromagnet becomes a paramagnet.** The Curie temperature of iron is 1043 K, considerably higher than that of most other ferromagnets.

Even below the Curie temperature, you may not notice that **a piece of iron is magnetized.** This is because a large chunk of iron ordinarily divides itself into domains that are microscopic in size but still contain billions of atomic dipoles. **Within each domain, the material is magnetized, but the magnetic field created by all the dipoles in one domain gives neighboring domains a tendency to magnetize in the opposite direction. (Put two ordinary bar magnets side by side and you’ll see why.) Because there are so many domains, with about as many pointing one way as another, the material as a whole has no net magnetization.** However, if you heat a chunk of iron in the presence of an external magnetic field, this field can overcome the interaction between domains and cause essentially all the dipoles to line up parallel. Remove the external field after the material has cooled to room temperature, and the ferromagnetic interaction prevents any significant realigning. You then have a “permanent” magnet.

### **What is the Ising Model?**
The **Ising model** is a mathematical model in statistical mechanics used to describe **phase transitions in ferromagnetic materials**. Named after the physicist Ernst Ising, who introduced it in his 1924 PhD thesis, the model consists of discrete variables called spins that represent magnetic dipole moments of atomic spins. These spins can be in one of two states, typically denoted as $+1$ (up) or $-1$ (down).

The **total energy (Hamiltonian)** of a spin configuration is given by:
   
   ${H = -J \sum_{\langle i, j \rangle} s_i s_j - h \sum_i s_i}$ where ${\langle i, j \rangle}$ denotes summation over neighboring pairs of spins, and $h$ is an external magnetic field.

The **interaction energy** between two neighboring spins $i$ and $j$ is given by:

   ${E_{ij} = -J s_i s_j}$ where $s_i$ and $s_j$ are the spins, and $J$ is the interaction constant.
   
   If $J > 0$, the interaction is ferromagnetic (favoring alignment), and if $J < 0$, the interaction is antiferromagnetic (favoring opposite alignment).

### **Exact Solutions for the Ising Model**
Exact solutions for the Ising model exist for certain cases. Specifically:

- **1D Ising Model:** There is an exact solution for the one-dimensional Ising model. You can learn about this in the Statistical Mechanics class offered in the following fall semester.
- **2D Ising Model:** Lars Onsager provided an exact solution for the two-dimensional Ising model without an external magnetic field.

### **Why Simulate the Ising Model if We Have Exact Solutions?**

- **Presence of an External Magnetic Field:** The exact solutions for the Ising model do not extend to cases where an external magnetic field is applied. Simulations allow us to study the system under these more complex conditions.

- **Non-Equilibrium Systems:** The exact solutions assume that the system is in equilibrium. However, many interesting and important physical phenomena occur in non-equilibrium systems. Simulations enable us to explore these dynamics and understand the behavior of systems as they evolve over time, approach equilibrium, or exhibit steady-state non-equilibrium behavior.

- **Higher Dimensions:** Exact solutions do not exist for the Ising model in dimensions higher than two. As the dimensionality increases, the complexity of the interactions makes it impossible to derive exact analytical solutions. Simulations become the primary method to study and understand the behavior of these higher-dimensional systems.


### **Import Module**

In [ ]:
!pip install numpy matplotlib ipywidgets pillow

!jupyter nbextension enable --py widgetsnbextension --sys-prefix
!jupyter nbextension enable --py --sys-prefix widgetsnbextension

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.2 MB/s eta 0:00:00
Enabling notebook extension jupyter-js-widgets/extension...
Paths used for configuration of notebook: 
    	/usr/etc/jupyter/nbconfig/notebook.json
Paths used for configuration of notebook: 
    	
      - Validating: OK
Paths used for configuration of notebook: 
    	/usr/etc/jupyter/nbconfig/notebook.json
Enabling notebook extension jupyter-js-widgets/extension...
Paths used for configuration of notebook: 
    	/usr/etc/jupyter/nbconfig/notebook.json
Paths used for configuration of notebook: 
    	
      - Validating: OK
Paths used for configuration of notebook: 
    	/usr/etc/jupyter/nbconfig/notebook.json


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, VBox, Label
from PIL import Image

### **Ising Model Simulation in Python**

**Setting neighbors for each spin site**

In [ ]:
L_x = 32
L_y = 32
number_of_sites = L_x * L_y
spin = (np.full(number_of_sites, -1))

neighbors = np.zeros((number_of_sites, 4),dtype=int)

for i in range(number_of_sites):
  x1 = i % L_x # %: Modulus ex) 5%2=1
  y1 = i // L_x # // Floor division ex)7//2=3

  # Neighbors considering periodic boundary conditions

  #Left
  if (x1==0):
    neighbors[i, 0]= i + L_x - 1
  else:
    neighbors[i, 0]= i - 1

  #Right
  if (x1 == L_x-1):
    neighbors[i, 1] = i - (L_x - 1)
  else:
    neighbors[i, 1] = i + 1


  #up
  if (y1 == 0):
    neighbors[i, 2] = i + L_x * (L_y - 1)
  else:
    neighbors[i, 2] = i - L_x

  #Down
  if (y1==L_y - 1):
    neighbors[i, 3] = i - L_x * (L_y - 1)
  else:
    neighbors[i, 3] = i + L_x

### **Expected questions**
**1. For representing the location of each spin sites via (x1, y1), why is modulus and floor division used?**
- When i is divided by L_x, the remainder (i % L_x) gives the column index within the current row. This is because each row contains L_x elements, and the modulo operation cycles through these columns.

- When i is divided by L_x, the quotient (i // L_x) gives the row index. This is because each complete set of L_x elements forms a new row.

- **Example**

   0 1 2 3

   4 5 6 7

   8 9 10 11

  For i = 7 :

  x1 = 7 % 4 = 3 (colum index)

  y1 = 7 // 4 = 1 (row index)



### **2. How does the code satisfy the periodic boundary condition?**
- **Left Neighbor**

 When x1 is 0, the site is on the left edge of the grid. The left neighbor wraps around to the last column of the same row (i + L_x - 1). Otherwise, the left neighbor is simply the previous site in the same row (i - 1).

- **Right Neighbor**

 If x1 is L_x - 1, the site is on the right edge of the grid. Its right neighbor wraps around to the first column of the same row (i - (L_x - 1)). Otherwise, the right neighbor is simply the next site in the same row (i + 1).

- **Down Neighbor**

 If y1 is 0, the site is on the top edge of the grid. Its down neighbor wraps around to the site at the bottom of the same column (i + L_x * (L_y - 1)). Otherwise, the down neighbor is simply the site directly above it (i - L_x).

- **Up Neighbor**

 If y1 is L_y - 1, the site is on the bottom edge of the grid. Its up neighbor wraps around to the site at the top of the same column (i - L_x * (L_y - 1)). Otherwise, the up neighbor is simply the site directly below it (i + L_x).



In [ ]:
print(neighbors)

[[  31    1  992   32]
 [   0    2  993   33]
 [   1    3  994   34]
 ...
 [1020 1022  989   29]
 [1021 1023  990   30]
 [1022  992  991   31]]


In [ ]:
# Functions for visualization
# This code is only for visualization and can be neglected if you are focusing on the Ising model simulation itself.

def display_spin_field(spin, scale_factor=10):
    lattice = spin.reshape((L_x, L_y))
    img = Image.fromarray(np.uint8((lattice + 1) * 0.5 * 255))  # 0 ... 255
    img = img.resize((img.width * scale_factor, img.height * scale_factor), Image.NEAREST)
    return img

def display_ising_sequence(images, magnetizations):
    magnetization_label = Label()

    def _show(frame=(0, len(images) - 1)):
        img = display_spin_field(images[frame])
        magnetization_label.value = f"Magnetization: {magnetizations[frame]}"
        display(img)

    interact(_show)
    display(VBox([magnetization_label]))

In [ ]:
def initialize_spin(spin, pole):
  if pole == 1:
    for i in range(number_of_sites):
      spin[i]= 1

  elif pole == -1:
    for i in range(number_of_sites):
      spin[i]= -1


def initialize_spin_random(spin):
    spin[:] = np.random.choice([-1, 1], size=number_of_sites)

In [ ]:
def delta_nrg(spin, chosen_site, field, bonding):
  de = 0.0
  s1 = spin[chosen_site]

  for i in range(4):
    s2 = spin[neighbors[chosen_site][i]]
    de += 2.0 * bonding * s1 * s2

  de += 2.0 * field * s1

  return de

def lattice_nrg(spin, field, bonding):
  nrg = 0.0

  for i in range(number_of_sites):
    s1 = spin[i]
    nrg -= field * s1

    for j in range(4):
      s2 = spin[neighbors[i][j]]
      nrg -= 0.5 * bonding * s1 * s2

  return nrg

def lattice_mag(spin):
    return np.sum(spin)

### **The Metropolis Algorithm for Simulating the Ising Model**

The Metropolis algorithm is a crucial method used in Monte Carlo simulations to study the Ising model, particularly for systems where exact solutions are not available or are difficult to compute. Here, we'll explain how the algorithm works and why it's effective.

**Monte Carlo Simulation**

In the context of a medium-sized, two-dimensional Ising model on a square lattice (e.g., 10×10 with 100 dipoles), it's computationally infeasible to consider all possible states due to their vast number. Instead, Monte Carlo summation (or integration) uses random sampling to estimate thermodynamic quantities like average energy and magnetization.

However, a naive Monte Carlo approach, which samples states purely at random, is inefficient because it misses the most probable states, especially at low temperatures. **The Metropolis algorithm addresses this inefficiency by generating a subset of states that reflect the correct Boltzmann distribution.**

**The Metropolis Algorithm Steps**

1. **Initialization**: Start with an arbitrary initial state of the system.
2. **State Selection**: Choose a spin at random and consider flipping it.
3. **Energy Calculation**: Compute the energy difference $\Delta E$ that would result from flipping the chosen spin.
4. **Decision Making**:
   - If $\Delta E \leq 0$, accept the flip because it lowers the system's energy.
   - If $\Delta E > 0$, accept the flip with a probability of $e^{-\Delta E / kT}$. This probability ensures that higher energy states are less likely but still possible, allowing the system to explore a range of states.
5. **Iteration**: Repeat the process many times to allow the system to sample various states.

The Metropolis algorithm efficiently generates states where low-energy configurations are more frequent, matching the Boltzmann distribution. This approach helps simulate the Ising model accurately, even for complex systems.


In [ ]:
def mc_step(spin, field, bonding, tee):
    chosen_site = np.random.randint(number_of_sites)

    de = delta_nrg(spin, chosen_site, field, bonding)

    prob = np.random.rand()
    entprod = 0.0

    if de <= 0:
        spin[chosen_site] = -spin[chosen_site]
        entprod = -de/tee
    else:
        glauber = np.exp(-de / tee)
        glauber = glauber / (glauber + 1.0)

        if prob < glauber:
            spin[chosen_site] = -spin[chosen_site]
            entprod = -de / tee

    return entprod

In [ ]:
images = []
magnetizations = []
entropy_productions = []

initialize_spin(spin, -1)
# initialize_spin(spin, +1)
#initialize_spin_random(spin)

field = 1.0
bonding = 1.0
tee = 1.5
# entprod = 0.0

for i in range(50000):
  # Adjust the step to store images and magnetization less frequently if needed
        _ = mc_step(spin, field, bonding, tee)
        images.append(spin.copy())
        magnetizations.append(lattice_mag(spin))


display_ising_sequence(images, magnetizations)

interactive(children=(IntSlider(value=24999, description='frame', max=49999), Output()), _dom_classes=('widget…

### **Objective**

Professor Kim has given me a challenging task, and I need your help! We need to explore different phase transitions and phases in the Ising model. Here’s what we aim to discover together:

1. ***Domain Formation:*** Within each domain, the material is magnetized, but the magnetic field created by all the dipoles in one domain gives neighboring domains a tendency to magnetize in the opposite direction. Because there are so many domains, with about as many pointing one way as another, the material as a whole has no net magnetization.

2. ***Spinodal Decomposition:*** We will observe phase separation in a quenched system without nucleation barriers. This happens when the system is rapidly cooled below the critical temperature without an external field, leading to spontaneous formation of domains.

3. ***Nucleation Decomposition:*** We will study the formation of stable nuclei in a metastable phase. This occurs when a uniform initial spin configuration transitions to a more stable phase by forming small regions (nuclei) of the new phase.

***Together, we will adjust control parameters such as temperature and external magnetic field, and try different initial conditions to observe these phenomena!!!***

Let’s dive in and help me complete my task from Professor Kim with this fascinating exploration of the Ising model!!!
